import type { Metadata } from "next";
import Link from "next/link";
import { LegalLayout, type LegalSection } from "@/components/legal/legal-layout";
import { SubprocessorTable } from "@/components/legal/subprocessor-table";

export const metadata: Metadata = {
  title: "Privacy Policy — QuantSentry",
  description:
    "How QuantSentry collects, uses, and protects personal data across our risk infrastructure platform.",
};

const subprocessors = [
  {
    name: "Amazon Web Services",
    purpose: "Application hosting, compute, and data storage",
    region: "EU (Ireland) and US (Virginia)",
  },
  {
    name: "Snowflake",
    purpose: "Analytical data warehousing for position and risk data",
    region: "EU (Frankfurt)",
  },
  {
    name: "Stripe",
    purpose: "Subscription billing and payment processing",
    region: "US",
  },
  {
    name: "Twilio SendGrid",
    purpose: "Transactional and account-related email delivery",
    region: "US",
  },
  {
    name: "Sentry",
    purpose: "Application error monitoring and diagnostics",
    region: "US",
  },
  {
    name: "Intercom",
    purpose: "Customer support messaging and in-app help",
    region: "US and EU",
  },
];

const sections: LegalSection[] = [
  {
    id: "information-we-collect",
    title: "Information we collect",
    content: (
      <>
        <p>
          We collect information in three broad categories: information you
          give us directly, information generated by your use of the
          service, and information about the position and market data you
          choose to connect for the purpose of risk analysis.
        </p>
        <ul>
          <li>
            <strong>Account and contact data</strong> — name, work email,
            employer, role, and phone number for you and other users your
            organisation adds.
          </li>
          <li>
            <strong>Customer data</strong> — position, exposure, and
            portfolio data your organisation connects from prime brokers,
            order management systems, and market data feeds so QuantSentry
            can compute risk metrics. This is processed as a data processor
            on your organisation&apos;s instructions, not as a controller.
          </li>
          <li>
            <strong>Usage data</strong> — pages viewed, queries run,
            features used, session length, and device and browser
            information, collected automatically as you use the product.
          </li>
          <li>
            <strong>Support data</strong> — anything you send us through
            support tickets, calls, or onboarding sessions, including
            screen recordings you choose to share.
          </li>
          <li>
            <strong>Billing data</strong> — invoicing contact details and
            payment metadata. Card numbers are handled directly by our
            payment processor and never touch our servers.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "how-we-use-it",
    title: "How we use it",
    content: (
      <>
        <p>We use the information above to:</p>
        <ul>
          <li>Provide, operate, and maintain the QuantSentry platform, including computing and displaying risk metrics.</li>
          <li>Authenticate users and enforce the access controls your organisation configures.</li>
          <li>Respond to support requests and provide onboarding and account management.</li>
          <li>Monitor system health, detect abuse, and debug incidents.</li>
          <li>Send service notices, security alerts, and — where you have opted in — product updates.</li>
          <li>Meet our legal, tax, audit, and regulatory obligations.</li>
        </ul>
        <p>
          We do not sell personal data, and we do not use customer position
          or portfolio data to train models shared across customers without
          separate written agreement.
        </p>
      </>
    ),
  },
  {
    id: "legal-bases",
    title: "Legal bases for processing (GDPR)",
    content: (
      <>
        <p>
          Where the UK GDPR or EU GDPR applies, we rely on the following
          legal bases:
        </p>
        <ul>
          <li>
            <strong>Contract</strong> — processing account and customer data
            necessary to perform the subscription agreement with your
            organisation.
          </li>
          <li>
            <strong>Legitimate interests</strong> — securing the platform,
            preventing fraud, and improving the product, balanced against
            your rights and interests.
          </li>
          <li>
            <strong>Consent</strong> — optional marketing communications and
            non-essential cookies, which you can withdraw at any time.
          </li>
          <li>
            <strong>Legal obligation</strong> — retaining records required
            by tax, accounting, or financial-services regulation.
          </li>
        </ul>
        <p>
          For customer data uploaded to the platform, your organisation is
          typically the data controller and QuantSentry acts as a data
          processor under a data processing agreement.
        </p>
      </>
    ),
  },
  {
    id: "sharing-and-subprocessors",
    title: "Sharing and subprocessors",
    content: (
      <>
        <p>
          We share personal data only where necessary to run the service,
          and always under contractual confidentiality and security
          obligations at least as protective as this policy:
        </p>
        <ul>
          <li>With subprocessors that host infrastructure, process billing, or support the product, listed below.</li>
          <li>With professional advisers such as auditors, insurers, and legal counsel.</li>
          <li>With a buyer or successor in the event of a merger, acquisition, or asset sale, subject to continued confidentiality.</li>
          <li>Where required to comply with a legal obligation, court order, or regulatory request.</li>
        </ul>
        <h3>Current subprocessors</h3>
        <p>
          We maintain the following subprocessors as of the date at the top
          of this page. We will provide notice before adding a new
          subprocessor that processes personal data on our behalf.
        </p>
        <SubprocessorTable rows={subprocessors} />
      </>
    ),
  },
  {
    id: "international-transfers",
    title: "International transfers",
    content: (
      <>
        <p>
          QuantSentry operates from offices in London and New York, and our
          infrastructure runs in the EU, UK, and US. Where personal data
          originating in the UK or EEA is transferred to a country without
          an adequacy decision, we rely on the UK International Data
          Transfer Addendum or the EU Standard Contractual Clauses, together
          with supplementary technical and organisational measures such as
          encryption in transit and at rest and restricted access controls.
        </p>
        <p>
          A copy of the relevant transfer mechanism is available on request
          from our data protection contact below.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    title: "Data retention",
    content: (
      <>
        <p>
          We retain account and usage data for as long as your organisation
          maintains an active subscription, plus a limited period afterward
          to handle billing disputes, legal claims, and reactivation
          requests. Customer position and portfolio data is retained
          according to the retention schedule agreed in your order form or
          data processing agreement, and is deleted or anonymised on
          request once that period ends, subject to any legal retention
          requirement we must comply with.
        </p>
        <p>
          Support tickets and audit logs relevant to security investigations
          are retained for a longer, defined period to satisfy our
          regulatory and contractual obligations to institutional clients.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    content: (
      <>
        <p>
          We apply technical and organisational measures appropriate to the
          sensitivity of financial position data, including:
        </p>
        <ul>
          <li>Encryption of data in transit (TLS 1.2+) and at rest.</li>
          <li>Role-based access controls and single sign-on support for customer accounts.</li>
          <li>Continuous monitoring, logging, and alerting on production systems.</li>
          <li>Regular penetration testing and independent security review.</li>
          <li>A documented incident response process, including customer notification timelines defined in our agreements.</li>
        </ul>
        <p>
          No system is completely secure. If you believe you have found a
          vulnerability, please contact us using the details below before
          disclosing it publicly.
        </p>
      </>
    ),
  },
  {
    id: "your-rights",
    title: "Your rights",
    content: (
      <>
        <p>
          Depending on where you are located, you may have the right to
          access, correct, delete, restrict, or port your personal data, and
          to object to certain processing, including direct marketing. UK
          and EEA individuals also have the right to lodge a complaint with
          their local supervisory authority — in the UK, the{" "}
          <a
            href="https://ico.org.uk"
            target="_blank"
            rel="noreferrer noopener"
          >
            Information Commissioner&apos;s Office
          </a>
          .
        </p>
        <p>
          Where QuantSentry processes customer data on your organisation&apos;s
          behalf as a processor, we will direct individual requests to your
          organisation as the controller, and assist your organisation in
          responding as required by our data processing agreement.
        </p>
        <p>
          To exercise a right directly with QuantSentry, use the contact
          details in the final section of this page.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and similar technologies",
    content: (
      <>
        <p>
          Our marketing site and product use a small number of cookies:
          strictly necessary cookies for authentication and session state,
          and, where you consent, analytics cookies that help us understand
          product usage. We do not use third-party advertising cookies.
        </p>
        <p>
          You can control non-essential cookies through the preference
          banner shown on first visit, or by adjusting your browser
          settings. Disabling strictly necessary cookies will prevent the
          product from functioning correctly.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    content: (
      <>
        <p>
          Questions about this policy, or requests relating to your personal
          data, can be directed to our data protection contact:
        </p>
        <ul>
          <li>Email: privacy@quantsentry.com</li>
          <li>QuantSentry Ltd — 20 St Thomas Street, London SE1 9RS, United Kingdom</li>
          <li>QuantSentry Inc. — 28 Liberty Street, New York, NY 10005, United States</li>
        </ul>
        <p>
          See our{" "}
          <Link href="/terms-of-service">terms of service</Link> for the
          contractual terms governing use of the platform, or visit{" "}
          <Link href="/contact-us">contact us</Link> for general enquiries.
        </p>
      </>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="14 August 2026"
      summary={
        <>
          QuantSentry (&ldquo;we&rdquo;, &ldquo;us&rdquo;) provides risk
          infrastructure software to systematic trading desks. This policy
          explains what personal data we collect from our customers and
          their users, why we collect it, who we share it with, and the
          rights you have over it. It does not describe how customer
          position or trading data itself is used — that is governed by
          your organisation&apos;s order form and our data processing
          agreement.
        </>
      }
      sections={sections}
    />
  );
}
